openapi: 3.0.1
info:
  title: IDPAY Welfare Portal Initiative API
  description: IDPAY Welfare Portal Initiative
  version: '1.0'
servers:
  - url: http://api-io.dev.cstar.pagopa.it/idpay/initiative
paths:
  "/{initiativeId}/beneficiary/view":
    get:
      tags:
        - initiative
      summary: Returns the detail of an active initiative
      operationId: getInitiativeBeneficiaryView
      parameters:
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiativeDTO'
              example:
                initiativeId: string
                initiativeName: string
                organizationId: string
                pdndToken: string
                status: string
                pdndCheck: true
                autocertificationCheck: true
                beneficiaryRanking: true
                general:
                  budget: 0
                  beneficiaryType: PF
                  beneficiaryKnown: true
                  beneficiaryBudget: 0
                  startDate: '2022-01-30'
                  endDate: '2022-01-30'
                  rankingStartDate: '2022-01-30'
                  rankingEndDate: '2022-01-30'
                additionalInfo:
                  serviceId: string
                  serviceName: string
                  argument: string
                  description: string
                beneficiaryRule:
                  selfDeclarationCriteria:
                    - _type: boolean
                      description: string
                      value:
                        - value1
                        - value2
                        - value3
                      code: string
                  automatedCriteria:
                    - authority: string
                      code: string
                      field: true
                      operator: string
                      value: string
                legal:
                  privacyLink: string
                  tcLink: string
                  regulationLink: string
                  dpiaLink: string
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '404':
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
  /summary:
    get:
      tags:
        - initiative
      summary: Returns the list of initiatives names for a specific organization
      description: Returns the list of initiatives names for a specific organization
      operationId: getInitativeSummary
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiativeSummaryArrayDTO'
              example:
                initiativeId: string
                initiativeName: string
                status: string
                creationDate: '2022-07-27T13:56:51.104Z'
                updateDate: '2022-07-27T13:56:51.104Z'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
  /{initiativeId}:
    get:
      tags:
        - initiative
      summary: Returns the detail of an active initiative
      description: Returns the detail of an active initiative
      operationId: getInitiativeDetail
      parameters:
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiativeDTO'
              example:
                initiativeId: string
                initiativeName: string
                organizationId: string
                pdndToken: string
                status: string
                pdndCheck: true
                autocertificationCheck: true
                beneficiaryRanking: true
                general:
                  budget: 0
                  beneficiaryType: PF
                  beneficiaryKnown: true
                  beneficiaryBudget: 0
                  startDate: '2022-01-30'
                  endDate: '2022-01-30'
                  rankingStartDate: '2022-01-30'
                  rankingEndDate: '2022-01-30'
                additionalInfo:
                  serviceId: string
                  serviceName: string
                  argument: string
                  description: string
                beneficiaryRule:
                  selfDeclarationCriteria:
                    - _type: boolean
                      description: string
                      value:
                        - value1
                        - value2
                        - value3
                      code: string
                  automatedCriteria:
                    - authority: string
                      code: string
                      field: true
                      operator: string
                      value: string
                legal:
                  privacyLink: string
                  tcLink: string
                  regulationLink: string
                  dpiaLink: string
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '404':
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
  /general:
    post:
      tags:
        - initiative
      summary: Save initiative and first subset of data 'general info'
      description: Save initiative and first subset of data 'general info'
      operationId: saveInitiativeGeneralInfo
      requestBody:
        description: Unique identifier of the subscribed initiative, IBAN of the citizen
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitiativeInfoDTO'
            example:
              general:
                budget: 0
                beneficiaryType: PF
                beneficiaryKnown: true
                beneficiaryBudget: 0
                startDate: '2022-01-30'
                endDate: '2022-01-30'
                rankingStartDate: '2022-01-30'
                rankingEndDate: '2022-01-30'
              additionalInfo:
                serviceId: string
                serviceName: string
                argument: string
                description: string
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiativeDTO'
              example:
                initiativeId: string
                initiativeName: string
                organizationId: string
                pdndToken: string
                status: string
                pdndCheck: true
                autocertificationCheck: true
                beneficiaryRanking: true
                general:
                  budget: 0
                  beneficiaryType: PF
                  beneficiaryKnown: true
                  beneficiaryBudget: 0
                  startDate: '2022-01-30'
                  endDate: '2022-01-30'
                  rankingStartDate: '2022-01-30'
                  rankingEndDate: '2022-01-30'
                additionalInfo:
                  serviceId: string
                  serviceName: string
                  argument: string
                  description: string
                beneficiaryRule:
                  selfDeclarationCriteria:
                    - _type: boolean
                      description: string
                      value: true
                      code: string
                  automatedCriteria:
                    - authority: string
                      code: string
                      field: true
                      operator: string
                      value: string
                legal:
                  privacyLink: string
                  tcLink: string
                  regulationLink: string
                  dpiaLink: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '404':
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
  /{initiativeId}/general:
    put:
      tags:
        - initiative
      summary: Update initiative and first subset of data 'general info'
      description: Update initiative and first subset of data 'general info'
      operationId: updateInitiativeGeneralInfo
      parameters:
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
      requestBody:
        description: Unique identifier of the subscribed initiative, IBAN of the citizen
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitiativeInfoDTO'
            example:
              general:
                budget: 0
                beneficiaryType: PF
                beneficiaryKnown: true
                beneficiaryBudget: 0
                startDate: '2022-01-30'
                endDate: '2022-01-30'
                rankingStartDate: '2022-01-30'
                rankingEndDate: '2022-01-30'
              additionalInfo:
                serviceId: string
                serviceName: string
                argument: string
                description: string
                channels:
                - type: web
                  contact: string
      responses:
        '204':
          description: No Content
          content:
            application/json: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '404':
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
  /{initiativeId}/beneficiary:
    put:
      tags:
        - initiative
      summary: Association of beneficiary rules to an initiative
      description: Association of beneficiary rules to an initiative
      operationId: updateInitiativeBeneficiary
      parameters:
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
      requestBody:
        description: Unique identifier of the subscribed initiative, instrument HPAN
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitiativeBeneficiaryRuleDTO'
            example:
              selfDeclarationCriteria:
                - _type: boolean
                  description: string
                  value:
                    - value1
                    - value2
                    - value3
                  code: string
              automatedCriteria:
                - authority: string
                  code: string
                  field: true
                  operator: string
                  value: string
      responses:
        '204':
          description: No Content
          content:
            application/json: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '404':
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
  /{initiativeId}/beneficiary/draft:
    put:
      tags:
        - initiative
      summary: Association of beneficiary rules to a draft initiative without validation
      description: Association of beneficiary rules to a draft initiative without validation
      operationId: updateInitiativeBeneficiaryDraft
      parameters:
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
      requestBody:
        description: Unique identifier of the subscribed initiative, instrument HPAN
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitiativeBeneficiaryRuleDTO'
            example:
              selfDeclarationCriteria:
                - _type: boolean
                  description: string
                  value:
                    - value1
                    - value2
                    - value3
                  code: string
              automatedCriteria:
                - authority: string
                  code: string
                  field: true
                  operator: string
                  value: string
      responses:
        '204':
          description: No Content
          content:
            application/json: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '404':
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
components:
  schemas:
    InitiativeAdditionalDTO:
      type: object
      properties:
        serviceId:
          type: string
        serviceName:
          type: string
        argument:
          type: string
        description:
          type: string
        channels:
          $ref: '#/components/schemas/ChannelArrayDTO'
    InitiativeLegalDTO:
      type: object
      properties:
        privacyLink:
          type: string
        tcLink:
          type: string
        regulationLink:
          type: string
        dpiaLink:
          type: string
    InitiativeGeneralDTO:
      type: object
      properties:
        budget:
          type: number
        beneficiaryType:
          enum:
            - PF
            - PG
          type: string
        beneficiaryKnown:
          type: boolean
        beneficiaryBudget:
          type: number
        startDate:
          type: string
          description: Start date
          format: date
          example: '2022-01-30'
        endDate:
          type: string
          description: Start date
          format: date
          example: '2022-01-30'
        rankingStartDate:
          type: string
          description: Start date
          format: date
          example: '2022-01-30'
        rankingEndDate:
          type: string
          description: Start date
          format: date
          example: '2022-01-30'
    AutomatedCriteriaDTO:
      type: object
      properties:
        authority:
          type: string
        code:
          type: string
        field:
          type: string
        operator:
          type: string
        value:
          type: string
    InitiativeDTO:
      type: object
      properties:
        initiativeId:
          type: string
        initiativeName:
          type: string
        organizationId:
          type: string
        pdndToken:
          type: string
        status:
          type: string
        pdndCheck:
          type: boolean
        autocertificationCheck:
          type: boolean
        beneficiaryRanking:
          type: boolean
        general:
          $ref: '#/components/schemas/InitiativeGeneralDTO'
        additionalInfo:
          $ref: '#/components/schemas/InitiativeAdditionalDTO'
        beneficiaryRule:
          $ref: '#/components/schemas/InitiativeBeneficiaryRuleDTO'
        legal:
          $ref: '#/components/schemas/InitiativeLegalDTO'
    InitiativeSummaryArrayDTO:
      type: array
      items:
        $ref: '#/components/schemas/InitiativeSummaryDTO'
    InitiativeSummaryDTO:
      type: object
      properties:
        initiativeId:
          type: string
        initiativeName:
          type: string
        status:
          type: string
        creationDate:
          type: string
          format: date-time
        updateDate:
          type: string
          format: date-time
    InitiativeInfoDTO:
      type: object
      properties:
        general:
          $ref: '#/components/schemas/InitiativeGeneralDTO'
        additionalInfo:
          $ref: '#/components/schemas/InitiativeAdditionalDTO'
    ChannelArrayDTO:
      type: array
      items:
        $ref: '#/components/schemas/ChannelDTO'
    ChannelDTO:
      type: object
      properties:
        type: 
          enum:
          - web
          - email
          - mobile
          type: string
        contact: 
          type: string
    ErrorDTO:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    AnyOfInitiativeBeneficiaryRuleDTOSelfDeclarationCriteriaItems:
      type: object
      anyOf:
        - $ref: '#/components/schemas/SelfCriteriaBoolDTO'
        - $ref: '#/components/schemas/SelfCriteriaMultiDTO'
      description: List of possible self criteria
    InitiativeBeneficiaryRuleDTO:
      type: object
      properties:
        selfDeclarationCriteria:
          type: array
          items:
            $ref: '#/components/schemas/AnyOfInitiativeBeneficiaryRuleDTOSelfDeclarationCriteriaItems'
          description: List of generic contents inside Customer
        automatedCriteria:
          type: array
          items:
            $ref: '#/components/schemas/AutomatedCriteriaDTO'
    SelfCriteriaBoolDTO:
      type: object
      properties:
        _type:
          enum:
            - boolean
          type: string
        description:
          type: string
        value:
          type: boolean
        code:
          type: string
    SelfCriteriaMultiDTO:
      title: SelfCriteriaMultiDTO
      type: object
      properties:
        _type:
          enum:
            - multi
          type: string
        description:
          type: string
        value:
          type: array
          items:
            type: string
          example:
            - value1
            - value2
            - value3
        code:
          type: string
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
security:
  - Bearer: []
tags:
  - name: initiative
    description: ''
