openapi: 3.0.3

info:
  title: EMD TPP NETWORK TESTING API
  version: '1.0'
  description: |-
    EMD TPP NETWORK TESTING
  contact:
    name: PagoPA S.p.A.
    email: cstar@pagopa.it

servers:
  - description: Development Test
    url: https://api-io.dev.cstar.pagopa.it/emd/mil/tpp
    x-internal: true
  - description: User Acceptance Test
    url: https://api-io.uat.cstar.pagopa.it/emd/mil/tpp
    x-internal: true

tags:
  - name: Network Testing
    description: 'Testing network connection'
paths:

  '/network/connection/{tppName}':
    get:
      tags:
        - Network Testing
      summary: >-
        ENG: Returns the confirm of network connection from TPP to PagoPA
      operationId: getNetworkConnection
      description: Get network connection info
      security:
        - oAuth2_dev: []  #per DEV
        #- oAuth2_uat: [] #per UAT
      parameters:
        - name: Accept-Language
          in: header
          description: 'ENG: Language - IT: Lingua'
          schema:
            type: string
            pattern: "^[ -~]{2,5}$"
            minLength: 2
            maxLength: 5
            example: it-IT
            default: it-IT
          required: true
        - name: tppName
          in: path
          description: "Company Name"
          required: true
          schema:
            type: string
            pattern: "^[ -~]{1,70}$"
            minLength: 1
            maxLength: 70
            example: "BancaX"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TppNetworkConnectionResponse'
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_BAD_REQUEST
                message: Something went wrong handling the request
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_AUTHENTICATION_FAILED
                message: Something went wrong with authentication
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '404':
          description: The TPP was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_NOT_ONBOARDED
                message: Tpp not onboarded
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_TOO_MANY_REQUESTS
                message: Too many requests
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_GENERIC_ERROR
                message: Application error
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'

components:
  schemas:

    AccessControlAllowOrigin:
      description: Indicates whether the response can be shared with requesting code from the given origin
      type: string
      pattern: "^[ -~]{1,2048}$"
      minLength: 1
      maxLength: 2048

    RateLimitLimit:
      description: The number of allowed requests in the current period
      type: integer
      format: int32
      minimum: 1
      maximum: 240

    RateLimitReset:
      description: The number of seconds left in the current period
      type: integer
      format: int32
      minimum: 1
      maximum: 60

    RetryAfter:
      description: The number of seconds to wait before allowing a follow-up request
      type: integer
      format: int32
      minimum: 1
      maximum: 240



    TppNetworkConnectionResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - PAGOPA_NETWORK_TEST
          description: |-
            "ENG: Message code: PAGOPA_NETWORK_TEST: BancaX has reached our systems,
             - IT: Codice messaggio: PAGOPA_NETWORK_TEST: BancaX ha raggiunto i nostri sistemi"
        message:
          type: string
          description: 'ENG: Messagge - IT: Messaggio'
          maxLength: 250
          pattern: "^[\\w\\s.,!?'\"-]+$"
          example: "BancaX has reached our systems"


    TPPErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - TPP_BAD_REQUEST
            - TPP_TOO_MANY_REQUESTS
            - TPP_GENERIC_ERROR
            - TPP_AUTHENTICATION_FAILED
          description: |-
            "ENG: Error code: TPP_BAD_REQUEST: Something went wrong handling the request,
             TPP_TOO_MANY_REQUESTS: Too many requests,
             TPP_GENERIC_ERROR: Application Error,
             TPP_AUTHENTICATION_FAILED: Something went wrong with authentication - IT: Codice di errore:
             TPP_BAD_REQUEST:  Qualcosa è andato storto durante l'invio della richiesta,
             TPP_TOO_MANY_REQUESTS: Troppe richieste,
             TPP_GENERIC_ERROR: Errore generico,
             TPP_AUTHENTICATION_FAILED: Qualcosa è andato storto con l'autenticazione,
        message:
          type: string
          description: 'ENG: Error message - IT: Messaggio di errore'
          maxLength: 250
          pattern: "^[\\w\\s.,!?'\"-]+$"

  # ============================================================================
  # Security schemes.
  # ============================================================================
  securitySchemes:
    oAuth2_dev:
      description: |
        A bearer token in the format of a JWS and conforms to the specifications
        included in RFC8725.
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api-mcshared.dev.cstar.pagopa.it/auth/token
          refreshUrl: https://api-mcshared.dev.cstar.pagopa.it/auth/token
          scopes: {}
    oAuth2_uat:
      description: |
        A bearer token in the format of a JWS and conforms to the specifications
        included in RFC8725.
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api-mcshared.uat.cstar.pagopa.it/auth/token
          refreshUrl: https://api-mcshared.uat.cstar.pagopa.it/auth/token
          scopes: {}
