openapi: 3.0.3

info:
  title: EMD TPP API
  version: '1.0'
  description: |-
    EMD TPP
  contact:
    name: Stefano D'Elia
    email: stefano11.delia@emeal.nttdata.com

servers:
  - description: Development Test
    url: https://api-io.dev.cstar.pagopa.it/emd/tpp
    x-internal: true
  - description: User Acceptance Test
    url: https://api-io.uat.cstar.pagopa.it/emd/tpp
    x-internal: true

security:
  - bearerAuth: [ ]

tags:
  - name: TPP
    description: 'TPP operation'
paths:
  '/':
    put:
      tags:
        - TPP
      summary: >-
        ENG: Update TPP consent state - IT: Aggiornamento dello stato dei consensi della TPP
      operationId: updateState
      description: Update TPP state
      parameters:
        - name: Accept-Language
          in: header
          description: 'ENG: Language - IT: Lingua'
          schema:
            type: string
            pattern: "^[ -~]{2,5}$"
            minLength: 2
            maxLength: 5
            example: it-IT
            default: it-IT
          required: true
      requestBody:
        description: 'ENG: TPP identifier and state - IT: Identificativo univoco della TPP e stato'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TppDTOUpdateState'
            example:
              tppId: 0e3bee29-8753-447c-b0da-1f7965558ec2_1706867960900
              state: false
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TppDTOWithDates'
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_BAD_REQUEST
                message: Something went wrong handling the request
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_AUTHENTICATION_FAILED
                message: Something went wrong with authentication
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '404':
          description: The TPP was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_NOT_ONBOARDED
                message: Tpp not onboarded
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_TOO_MANY_REQUESTS
                message: Too many requests
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_GENERIC_ERROR
                message: Application error
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
  '/update':
    put:
      tags:
        - TPP
      summary: >-
        ENG: Update TPP information - IT: Aggiorna le informazioni della TPP
      operationId: update
      description: Save TPP information
      parameters:
        - name: Accept-Language
          in: header
          description: 'ENG: Language - IT: Lingua'
          schema:
            type: string
            pattern: "^[ -~]{2,5}$"
            minLength: 2
            maxLength: 5
            example: it-IT
            default: it-IT
          required: true
      requestBody:
        description: 'ENG: TPP details - IT: Dettagli della TPP'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TppDTOTppIdRequired'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TppDTOWithDates'
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_BAD_REQUEST
                message: Something went wrong handling the request
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_AUTHENTICATION_FAILED
                message: Something went wrong with authentication
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '404':
          description: The TPP was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_NOT_ONBOARDED
                message: Tpp not onboarded
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_TOO_MANY_REQUESTS
                message: Too many requests
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_GENERIC_ERROR
                message: Application error
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
  '/save':
    post:
      tags:
        - TPP
      summary: >-
        ENG: Save TPP information - IT: Salva le informazioni della TPP
      operationId: save
      description: Save TPP information
      parameters:
        - name: Accept-Language
          in: header
          description: 'ENG: Language - IT: Lingua'
          schema:
            type: string
            pattern: "^[ -~]{2,5}$"
            minLength: 2
            maxLength: 5
            example: it-IT
            default: it-IT
          required: true
      requestBody:
        description: 'ENG: TPP details - IT: Dettagli della TPP'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TppDTO'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TppDTOWithDates'
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_BAD_REQUEST
                message: Something went wrong handling the request
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_AUTHENTICATION_FAILED
                message: Something went wrong with authentication
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '403':
          description: The TPP already onboarded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_ALREADY_ONBOARDED
                message: Tpp is already onboarded
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '404':
          description: The TPP was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_NOT_ONBOARDED
                message: Tpp not onboarded
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_TOO_MANY_REQUESTS
                message: Too many requests
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_GENERIC_ERROR
                message: Application error
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
  '/{tppId}':
    get:
      tags:
        - TPP
      summary: >-
        ENG: Returns the TPP detalil from tppId associated - IT: Ritorna il dettaglio della TPP attraverso il tppId
      operationId: get
      description: Get TPP detail from tppId
      parameters:
        - name: Accept-Language
          in: header
          description: 'ENG: Language - IT: Lingua'
          schema:
            type: string
            pattern: "^[ -~]{2,5}$"
            minLength: 2
            maxLength: 5
            example: it-IT
            default: it-IT
          required: true
        - name: tppId
          in: path
          description: 'ENG: Unique ID that identify TPP on PagoPA systems - IT: Identificativo univoco della TPP sui sistemi PagoPA'
          required: true
          schema:
            type: string
            pattern: "^[ -~]{1,50}$"
            minLength: 50
            maxLength: 50
            example: "0e3bee29-8753-447c-b0da-1f7965558ec2_1706867960900"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TppDTOWithDates'
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_BAD_REQUEST
                message: Something went wrong handling the request
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_AUTHENTICATION_FAILED
                message: Something went wrong with authentication
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '404':
          description: The TPP was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_NOT_ONBOARDED
                message: Tpp not onboarded
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_TOO_MANY_REQUESTS
                message: Too many requests
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TPPErrorDTO'
              example:
                code: TPP_GENERIC_ERROR
                message: Application error
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'



components:
  schemas:

    AccessControlAllowOrigin:
      description: Indicates whether the response can be shared with requesting code from the given origin
      type: string
      pattern: "^[ -~]{1,2048}$"
      minLength: 1
      maxLength: 2048

    RateLimitLimit:
      description: The number of allowed requests in the current period
      type: integer
      format: int32
      minimum: 1
      maximum: 240

    RateLimitReset:
      description: The number of seconds left in the current period
      type: integer
      format: int32
      minimum: 1
      maximum: 60

    RetryAfter:
      description: The number of seconds to wait before allowing a follow-up request
      type: integer
      format: int32
      minimum: 1
      maximum: 240

    TppDTOUpdateState:
      type: object
      required:
        - tppId
        - state
      description: "TPP information(Third Party Provider)"
      properties:
        tppId:
          type: string
          description: "Unique ID that identify TPP on PagoPA systems"
          pattern: "^[ -~]{1,50}$"
          minLength: 50
          maxLength: 50
          example: "0e3bee29-8753-447c-b0da-1f7965558ec2_1706867960900"
        state:
          type: boolean
          description: "Status active/inactive"
          example: true

    TppDTOTppIdRequired:
      type: object
      required:
        - tppId
        - entityId
        - businessName
        - legalAddress
        - messageUrl
        - authenticationUrl
        - authenticationType
        - contact
      description: "TPP information(Third Party Provider)"
      properties:
        tppId:
          type: string
          description: "Unique ID that identify TPP on PagoPA systems"
          pattern: "^[ -~]{1,50}$"
          minLength: 1
          maxLength: 50
          example: "0e3bee29-8753-447c-b0da-1f7965558ec2_1706867960900"
        entityId:
          type: string
          description: "Fiscal Code or P.IVA of the TPP"
          pattern: "^[A-Za-z0-9]{11,16}$"
          minLength: 11
          maxLength: 16
          example: "86363574890"
        idPsp:
          type: string
          description: "Id of Payment Service Provider"
          pattern: "^[A-Za-z0-9 ]+$"
          minLength: 1
          maxLength: 50
          example: "MasterCard 123"
        businessName:
          type: string
          description: "Company Name"
          pattern: "^[ -~]{1,70}$"
          minLength: 1
          maxLength: 70
          example: "MyBusiness Ltd"
        legalAddress:
          type: string
          description: "Company Legal Address"
          pattern: "^[ -~]{1,70}$"
          minLength: 1
          maxLength: 70
          example: "Via Washington, 13"
        messageUrl:
          type: string
          description: "URL to notify PUSH message"
          format: uri
          pattern: "^[ -~]{1,2048}$"
          minLength: 1
          maxLength: 2048
          example: "https://api.tpp.com/message"
        authenticationUrl:
          type: string
          description: "url for authentication"
          format: uri
          pattern: "^[ -~]{1,2048}$"
          minLength: 1
          maxLength: 2048
          example: "https://api.tpp.com/auth"
        authenticationType:
          type: string
          description: "authentication type"
          enum:
            - OAUTH2
          example: "OAUTH2"
        contact:
          $ref: '#/components/schemas/Contact'
        state:
          type: boolean
          description: "Status active/inactive"
          example: true

    TppDTO:
      type: object
      required:
        - entityId
        - businessName
        - legalAddress
        - messageUrl
        - authenticationUrl
        - authenticationType
        - contact
      description: "TPP information(Third Party Provider)"
      properties:
        entityId:
          type: string
          description: "Fiscal Code or P.IVA of the TPP"
          pattern: "^[A-Za-z0-9]{11,16}$"
          minLength: 11
          maxLength: 16
          example: "86363574890"
        idPsp:
          type: string
          description: "Id of Payment Service Provider"
          pattern: "^[A-Za-z0-9 ]+$"
          minLength: 1
          maxLength: 50
          example: "MasterCard 123"
        businessName:
          type: string
          description: "Company Name"
          pattern: "^[ -~]{1,70}$"
          minLength: 1
          maxLength: 70
          example: "MyBusiness Ltd"
        legalAddress:
          type: string
          description: "Company Legal Address"
          pattern: "^[ -~]{1,70}$"
          minLength: 1
          maxLength: 70
          example: "Via Washington, 13"
        messageUrl:
          type: string
          description: "URL to notify PUSH message"
          format: uri
          pattern: "^[ -~]{1,2048}$"
          minLength: 1
          maxLength: 2048
          example: "https://api.tpp.com/message"
        authenticationUrl:
          type: string
          description: "url for authentication"
          format: uri
          pattern: "^[ -~]{1,2048}$"
          minLength: 1
          maxLength: 2048
          example: "https://api.tpp.com/auth"
        authenticationType:
          type: string
          description: "authentication type"
          enum:
            - OAUTH2
          example: "OAUTH2"
        contact:
          $ref: '#/components/schemas/Contact'
        state:
          type: boolean
          description: "Status active/inactive"
          example: true


    Contact:
      type: object
      required:
        - name
        - number
        - email
      description: "Contact information about TPP"
      properties:
        name:
          type: string
          description: "Contact name"
          example: "John Doe"
          pattern: "^[ -~]{1,50}$"
          minLength: 1
          maxLength: 50
        number:
          type: string
          description: "Telephone number"
          example: "+393456780019"
          pattern: "^(\\+\\d{1,3})?\\d{8,15}$"
          minLength: 8
          maxLength: 15
        email:
          type: string
          description: "Contact email"
          example: "john.doe@tpp.com"
          format: email
          maxLength: 100


    TppDTOWithDates:
      allOf:
        - $ref: '#/components/schemas/TppDTOTppIdRequired'
        - type: object
          description: "TPP information with date fields"
          properties:
            creationDate:
              type: string
              format: date-time
              description: "The date and time when the TPP was created"
              example: "2023-10-01T12:00:40.695Z"
              maxLength: 30
              pattern: "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$"
            lastUpdateDate:
              type: string
              format: date-time
              description: "The date and time when the TPP was last updated"
              example: "2023-10-15T08:30:40.695Z"
              maxLength: 30
              pattern: "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$"

    TPPErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - TPP_BAD_REQUEST
            - TPP_NOT_ONBOARDED
            - TPP_TOO_MANY_REQUESTS
            - TPP_GENERIC_ERROR
            - TPP_AUTHENTICATION_FAILED
            - TPP_ALREADY_ONBOARDED
          description: |-
            "ENG: Error code: TPP_BAD_REQUEST: Something went wrong handling the request,
             TPP_NOT_ONBOARDED: TPP not onboarded,
             TPP_TOO_MANY_REQUESTS: Too many requests,
             TPP_GENERIC_ERROR: Application Error,
             TPP_AUTHENTICATION_FAILED: Something went wrong with authentication,
             TPP_ALREADY_ONBOARDED: Tpp is already onboarded - IT: Codice di errore:
             TPP_BAD_REQUEST:  Qualcosa è andato storto durante l'invio della richiesta,
             TPP_NOT_ONBOARDED: TPP non onboardata,
             TPP_TOO_MANY_REQUESTS: Troppe richieste,
             TPP_GENERIC_ERROR: Errore generico,
             TPP_AUTHENTICATION_FAILED: Qualcosa è andato storto con l'autenticazione,
             TPP_ALREADY_ONBOARDED: La TPP è già onboardata"
        message:
          type: string
          description: 'ENG: Error message - IT: Messaggio di errore'
          maxLength: 250
          pattern: "^[\\w\\s.,!?'\"-]+$"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
