openapi: 3.0.3
info:
  title: IDPAY Iban IO API
  description: |-
    IDPAY IBAN IO

    IDPAY Onboarding Workflow IO

    IDPAY Timeline IO

    IDPAY Wallet IO

  version: "1.0"
servers:
  - url: "https://api-io.dev.cstar.pagopa.it/idpay"
security:
  - bearerAuth: []
tags:
  - name: iban
    description: ""
  - name: onboarding
    description: ""
  - name: timeline
    description: ""
  - name: wallet
    description: ""
paths:
  "/iban/{iban}":
    get:
      tags:
        - iban
      summary: >-
        Returns the detail of the IBAN associated to the initiative by the
        citizen
      operationId: getIban
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
        - name: iban
          in: path
          description: The citizen iban
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IbanDTO"
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  /iban/:
    get:
      tags:
        - iban
      summary: Returns the list of iban associated to the citizen
      operationId: getIbanList
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IbanListDTO"
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  "/onboarding/service/{serviceId}":
    get:
      tags:
        - onboarding
      summary: Retrieves the initiative ID starting from the corresponding service ID
      operationId: getInitiativeData
      parameters:
        - name: serviceId
          in: path
          description: The service ID
          required: true
          schema:
            type: string
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
      responses:
        "200":
          description: Get successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InitiativeDataDTO"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  /onboarding/:
    put:
      tags:
        - onboarding
      summary: Acceptance of Terms & Conditions
      operationId: onboardingCitizen
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
      requestBody:
        description: Id of the initiative
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OnboardingPutDTO"
      responses:
        "204":
          description: Acceptance successful
          content:
            application/json: {}
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        '403':
          description: This onboarding is forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrerequisitesErrorDTO'
              example:
                code: 0
                message: string
                details: GENERIC_ERROR
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  /onboarding/initiative:
    put:
      tags:
        - onboarding
      summary: Check the initiative prerequisites
      operationId: checkPrerequisites
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
      requestBody:
        description: Id of the iniziative
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OnboardingPutDTO"
            example:
              initiativeId: string
      responses:
        "200":
          description: Check successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequiredCriteriaDTO"
        "202":
          description: Accepted - Request Taken Over
          content:
            application/json: {}
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "403":
          description: This onboarding is forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PrerequisitesErrorDTO"
              example:
                code: 0
                message: string
                details: GENERIC_ERROR
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  /onboarding/consent:
    put:
      tags:
        - onboarding
      summary: Save the consensus of both PDND and self-declaration
      operationId: consentOnboarding
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
      requestBody:
        description: >-
          Unique identifier of the subscribed initiative, flag for PDND
          acceptation and the list of accepted self-declared criteria
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConsentPutDTO"
      responses:
        "202":
          description: Accepted - Request Taken Over
          content:
            application/json: {}
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        '403':
          description: This onboarding is forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrerequisitesErrorDTO'
              example:
                code: 0
                message: string
                details: GENERIC_ERROR
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  "/onboarding/{initiativeId}/status":
    get:
      tags:
        - onboarding
      summary: Returns the actual onboarding status
      operationId: onboardingStatus
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Check successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OnboardingStatusDTO"
              example:
                status: ACCEPTED_TC
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  "/timeline/{initiativeId}":
    get:
      tags:
        - timeline
      summary: >-
        Returns the list of transactions and operations of an initiative of a
        citizen sorted by date (newest->oldest)
      operationId: getTimeline
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
        - name: operationType
          in: query
          description: Operation type filter
          schema:
            type: string
        - name: page
          in: query
          description: The number of the page
          schema:
            type: integer
        - name: size
          in: query
          description: "Number of items, default 3 - max 10"
          schema:
            type: integer
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimelineDTO"
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  "/timeline/{initiativeId}/{operationId}":
    get:
      tags:
        - timeline
      summary: Returns the detail of a transaction
      operationId: getTimelineDetail
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
        - name: operationId
          in: path
          description: The operation ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationDTO'
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  /wallet/:
    get:
      tags:
        - wallet
      summary: Returns the list of active initiatives of a citizen
      operationId: getWallet
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WalletDTO"
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  "/wallet/{initiativeId}/detail":
    get:
      tags:
        - wallet
      summary: Returns the detail of an initiative
      operationId: getInitiativeBeneficiaryDetail
      parameters:
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiativeDetailDTO'
        '404':
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  "/wallet/{initiativeId}":
    get:
      tags:
        - wallet
      summary: Returns the detail of an active initiative of a citizen
      operationId: getWalletDetail
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InitiativeDTO"
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  "/wallet/{initiativeId}/iban":
    put:
      tags:
        - wallet
      summary: Association of an IBAN to an initiative
      operationId: enrollIban
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
      requestBody:
        description: "Unique identifier of the subscribed initiative, IBAN of the citizen"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IbanPutDTO"
            example:
              iban: string
              description: string
      responses:
        "200":
          description: Enrollment OK
          content:
            application/json: {}
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  "/wallet/{initiativeId}/instruments/{idWallet}":
    put:
      tags:
        - wallet
      summary: Association of a payment instrument to an initiative
      operationId: enrollInstrument
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
        - name: idWallet
          in: path
          description: A unique id that identifies a payment method
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Enrollment OK
          content:
            application/json: {}
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  "/wallet/{initiativeId}/instruments":
    get:
      tags:
        - wallet
      summary: >-
        Returns the list of payment instruments associated to the initiative by
        the citizen
      operationId: getInstrumentList
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InstrumentListDTO"
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  "/wallet/{initiativeId}/instruments/{instrumentId}":
    delete:
      tags:
        - wallet
      summary: Delete a payment instrument from an initiative
      operationId: deleteInstrument
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
        - name: instrumentId
          in: path
          description: "A unique id, internally detached, which identifies a payment method"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Delete OK
          content:
            application/json: {}
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  "/wallet/{initiativeId}/unsubscribe":
    delete:
      tags:
        - wallet
      summary: Unsubscribe to an initiative
      operationId: unsubscribe
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Unsubscribe OK
          content:
            application/json: {}
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  "/wallet/{initiativeId}/status":
    get:
      tags:
        - wallet
      summary: Returns the actual wallet status
      operationId: getWalletStatus
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
        - name: initiativeId
          in: path
          description: The initiative ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Check successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WalletStatusDTO"
              example:
                status: NOT_REFUNDABLE_ONLY_IBAN
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "404":
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "429":
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
        "500":
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
              example:
                code: 0
                message: string
  '/wallet/instrument/{idWallet}/initiatives':
    get:
      tags:
        - wallet
      summary: Returns the initiatives list associated to a payment instrument
      operationId: getInitiativesWithInstrument
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
            example: it-IT
            default: it-IT
          required: true
        - name: idWallet
          in: path
          description: The ID Wallet
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiativesWithInstrumentDTO'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                code: 0
                message: string
components:
  schemas:
    IbanDTO:
      type: object
      required:
        - iban
        - checkIbanStatus
        - description
        - channel
      properties:
        iban:
          type: string
        checkIbanStatus:
          type: string
        holderBank:
          type: string
        description:
          type: string
        channel:
          type: string
    IbanListDTO:
      type: object
      required:
        - ibanList
      properties:
        ibanList:
          type: array
          items:
            $ref: "#/components/schemas/IbanDTO"
          description: The list of iban of a citizen
    ErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    ConsentPutDTO:
      title: ConsentPutDTO
      type: object
      required:
        - initiativeId
        - pdndAccept
        - selfDeclarationList
      properties:
        initiativeId:
          type: string
          description: Unique identifier of the subscribed initiative
        pdndAccept:
          type: boolean
          description: Flag for PDND acceptation
        selfDeclarationList:
          type: array
          items:
            $ref: "#/components/schemas/SelfConsentDTO"
          description: The list of accepted self-declared criteria
    SelfConsentDTO:
      oneOf:
        - $ref: "#/components/schemas/SelfConsentBoolDTO"
        - $ref: "#/components/schemas/SelfConsentMultiDTO"
    OnboardingPutDTO:
      title: OnboardingPutDTO
      type: object
      required:
        - initiativeId
      properties:
        initiativeId:
          type: string
          description: Unique identifier of the subscribed initiative
    OnboardingStatusDTO:
      title: OnboardingStatusDTO
      type: object
      required:
        - status
      properties:
        status:
          enum:
            - ACCEPTED_TC
            - ON_EVALUATION
            - ONBOARDING_KO
            - ELIGIBLE_KO
            - ONBOARDING_OK
            - UNSUBSCRIBED
            - INVITED
            - ELIGIBLE
            - SUSPENDED
          type: string
          description: actual status of the citizen onboarding for an initiative
    RequiredCriteriaDTO:
      type: object
      required:
        - pdndCriteria
        - selfDeclarationList
      properties:
        pdndCriteria:
          type: array
          items:
            $ref: "#/components/schemas/PDNDCriteriaDTO"
          description: The list of control made with PDND platform
        selfDeclarationList:
          type: array
          items:
            $ref: "#/components/schemas/SelfDeclarationDTO"
          description: The list of required self-declared criteria
    SelfDeclarationDTO:
      oneOf:
        - $ref: "#/components/schemas/SelfDeclarationBoolDTO"
        - $ref: "#/components/schemas/SelfDeclarationMultiDTO"
    PDNDCriteriaDTO:
      type: object
      required:
        - code
        - description
        - value
        - authority
      properties:
        code:
          type: string
        description:
          type: string
        value:
          type: string
          description: >-
            The expected value for the criteria. It is used in conjunction with
            the operator to define a range or an equality over that criteria.
        value2:
          type: string
          description: >-
            In situations where the operator expects two values (e.g BETWEEN)
            this field is populated
        operator:
          type: string
          description: Represents the relation between the criteria and the value field
        authority:
          type: string
    SelfDeclarationBoolDTO:
      type: object
      required:
        - _type
        - code
        - description
        - value
      properties:
        _type:
          type: string
          enum:
            - boolean
        code:
          type: string
        description:
          type: string
        value:
          type: boolean
    SelfDeclarationMultiDTO:
      type: object
      required:
        - _type
        - code
        - description
        - value
      properties:
        _type:
          type: string
          enum:
            - multi
        code:
          type: string
        description:
          type: string
        value:
          type: array
          items:
            type: string
    SelfConsentBoolDTO:
      type: object
      required:
        - _type
        - code
        - accepted
      properties:
        _type:
          type: string
          enum:
            - boolean
        code:
          type: string
        accepted:
          type: boolean
    SelfConsentMultiDTO:
      type: object
      required:
        - _type
        - code
        - value
      properties:
        _type:
          type: string
          enum:
            - multi
        code:
          type: string
        value:
          type: string
    InitiativeDataDTO:
      type: object
      required:
        - initiativeId
        - initiativeName
        - description
        - organizationId
        - organizationName
        - tcLink
        - privacyLink
      properties:
        initiativeId:
          type: string
        initiativeName:
          type: string
        description:
          type: string
        organizationId:
          type: string
        organizationName:
          type: string
        tcLink:
          type: string
        privacyLink:
          type: string
        logoURL:
          type: string
    OperationDTO:
      oneOf:
        - $ref: '#/components/schemas/TransactionDetailDTO'
        - $ref: '#/components/schemas/InstrumentOperationDTO'
        - $ref: '#/components/schemas/IbanOperationDTO'
        - $ref: '#/components/schemas/OnboardingOperationDTO'
        - $ref: '#/components/schemas/RefundOperationDTO'
        - $ref: '#/components/schemas/SuspendOperationDTO'
    TimelineDTO:
      type: object
      required:
        - lastUpdate
        - operationList
        - pageNo
        - pageSize
        - totalElements
        - totalPages
      properties:
        lastUpdate:
          type: string
          description: date of the last update
          format: date-time
        operationList:
          type: array
          items:
            $ref: '#/components/schemas/OperationListDTO'
          description: the list of transactions and operations of an initiative of a citizen
        pageNo:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
    OperationListDTO:
      description: Complex type for items in the operation list
      oneOf:
        - $ref: "#/components/schemas/TransactionOperationDTO"
        - $ref: "#/components/schemas/InstrumentOperationDTO"
        - $ref: "#/components/schemas/RejectedInstrumentOperationDTO"
        - $ref: "#/components/schemas/IbanOperationDTO"
        - $ref: "#/components/schemas/OnboardingOperationDTO"
        - $ref: "#/components/schemas/RefundOperationDTO"
        - $ref: '#/components/schemas/SuspendOperationDTO'
    RejectedInstrumentOperationDTO:
      type: object
      required:
        - operationId
        - operationType
        - operationDate
        - brandLogo
        - brand
        - maskedPan
        - channel
      properties:
        operationId:
          type: string
        operationType:
          enum:
            - REJECTED_ADD_INSTRUMENT
            - REJECTED_DELETE_INSTRUMENT
          type: string
        operationDate:
          type: string
          format: date-time
        brandLogo:
          type: string
        brand:
          type: string
        instrumentId:
          type: string
        maskedPan:
          type: string
        channel:
          type: string
    TransactionDetailDTO:
      type: object
      required:
        - operationId
        - operationType
        - operationDate
        - brandLogo
        - brand
        - maskedPan
        - amount
        - accrued
        - circuitType
        - idTrxIssuer
        - idTrxAcquirer
      properties:
        operationId:
          type: string
        operationType:
          enum:
            - TRANSACTION
            - REVERSAL
          type: string
        brandLogo:
          type: string
        brand:
          type: string
        maskedPan:
          type: string
        amount:
          type: number
        accrued:
          type: number
        operationDate:
          type: string
          format: date-time
        circuitType:
          type: string
          description: >-
            00-> Bancomat, 01->Visa, 02->Mastercard, 03->Amex, 04->JCB,
            05->UnionPay, 06->Diners, 07->PostePay, 08->BancomatPay,
            09->Satispay, 10->PrivateCircuit
        idTrxIssuer:
          type: string
        idTrxAcquirer:
          type: string
    InstrumentOperationDTO:
      type: object
      required:
        - operationId
        - operationType
        - operationDate
        - brandLogo
        - brand
        - maskedPan
        - channel
      properties:
        operationId:
          type: string
        operationType:
          enum:
            - ADD_INSTRUMENT
            - DELETE_INSTRUMENT
          type: string
        operationDate:
          type: string
          format: date-time
        brandLogo:
          type: string
        brand:
          type: string
        maskedPan:
          type: string
        channel:
          type: string
    IbanOperationDTO:
      type: object
      required:
        - operationId
        - operationType
        - operationDate
        - iban
        - channel
      properties:
        operationId:
          type: string
        operationType:
          enum:
            - ADD_IBAN
          type: string
        operationDate:
          type: string
          format: date-time
        iban:
          type: string
        channel:
          type: string
    OnboardingOperationDTO:
      type: object
      required:
        - operationId
        - operationType
        - operationDate
      properties:
        operationId:
          type: string
        operationType:
          enum:
            - ONBOARDING
          type: string
        operationDate:
          type: string
          format: date-time
    RefundOperationDTO:
      type: object
      required:
        - operationId
        - operationType
        - operationDate
        - amount
      properties:
        operationId:
          type: string
        operationType:
          enum:
            - PAID_REFUND
            - REJECTED_REFUND
          type: string
        operationDate:
          type: string
          format: date
        amount:
          type: number
    SuspendOperationDTO:
      type: object
      required:
        - operationId
        - operationType
        - operationDate
      properties:
        operationId:
          type: string
        operationType:
          enum:
            - SUSPENDED
          type: string
        operationDate:
          type: string
          format: date-time
    TransactionOperationDTO:
      type: object
      required:
        - operationId
        - operationType
        - operationDate
        - brandLogo
        - brand
        - maskedPan
        - amount
        - accrued
        - circuitType
      properties:
        operationId:
          type: string
        operationType:
          enum:
            - TRANSACTION
            - REVERSAL
          type: string
        operationDate:
          type: string
          format: date-time
        brandLogo:
          type: string
        brand:
          type: string
        maskedPan:
          type: string
        amount:
          type: number
        accrued:
          type: number
        circuitType:
          type: string
          description: >-
            00-> Bancomat, 01->Visa, 02->Mastercard, 03->Amex, 04->JCB,
            05->UnionPay, 06->Diners, 07->PostePay, 08->BancomatPay,
            09->Satispay, 10->PrivateCircuit
    IbanPutDTO:
      title: IbanPutDTO
      type: object
      required:
        - iban
        - description
      properties:
        iban:
          type: string
          description: IBAN of the citizen
        description:
          type: string
          description: further information about the iban
    WalletStatusDTO:
      title: WalletStatusDTO
      type: object
      required:
        - status
      properties:
        status:
          enum:
            - NOT_REFUNDABLE_ONLY_IBAN
            - NOT_REFUNDABLE_ONLY_INSTRUMENT
            - REFUNDABLE
            - NOT_REFUNDABLE
            - UNSUBSCRIBED
            - SUSPENDED
          type: string
          description: actual status of the citizen wallet for an initiative
    WalletDTO:
      type: object
      required:
        - initiativeList
      properties:
        initiativeList:
          type: array
          items:
            $ref: "#/components/schemas/InitiativeDTO"
          description: The list of active initiatives of a citizen
    InstrumentListDTO:
      type: object
      required:
        - instrumentList
      properties:
        instrumentList:
          type: array
          items:
            $ref: "#/components/schemas/InstrumentDTO"
          description: >-
            The list of payment instruments associated to the initiative by the
            citizen
    InstrumentDTO:
      title: InstrumentDTO
      type: object
      required:
        - instrumentId
      properties:
        idWallet:
          type: string
          description: Wallet's id provided by the Payment manager
        instrumentId:
          type: string
          description: Payment instrument id
        maskedPan:
          type: string
          description: Masked Pan
        channel:
          type: string
        brandLogo:
          type: string
          description: "Card's brand as mastercard, visa, ecc."
        brand:
          type: string
        status:
          enum:
            - ACTIVE
            - PENDING_ENROLLMENT_REQUEST
            - PENDING_DEACTIVATION_REQUEST
          type: string
          description: The status of the instrument
        activationDate:
          type: string
          format: date-time
    InitiativeDTO:
      type: object
      required:
        - initiativeId
        - status
        - endDate
        - nInstr
      properties:
        initiativeId:
          type: string
        initiativeName:
          type: string
        status:
          enum:
            - NOT_REFUNDABLE_ONLY_IBAN
            - NOT_REFUNDABLE_ONLY_INSTRUMENT
            - REFUNDABLE
            - NOT_REFUNDABLE
            - UNSUBSCRIBED
            - SUSPENDED
          type: string
        endDate:
          type: string
          format: date
        amount:
          type: number
        accrued:
          type: number
        refunded:
          type: number
        lastCounterUpdate:
          type: string
          format: date-time
        iban:
          type: string
        nInstr:
          type: integer
          format: int32
    InitiativesWithInstrumentDTO:
      type: object
      required:
        - idWallet
        - maskedPan
        - brand
        - initiativeList
      properties:
        idWallet:
          type: string
        maskedPan:
          type: string
        brand:
          type: string
        initiativeList:
          type: array
          items:
            $ref: '#/components/schemas/InitiativesStatusDTO'
          description: The list of the initiatives status related to a payment instrument
    InitiativesStatusDTO:
      type: object
      required:
        - initiativeId
        - initiativeName
        - status
      properties:
        initiativeId:
          type: string
        initiativeName:
          type: string
        idInstrument:
          type: string
        status:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
            - PENDING_ENROLLMENT_REQUEST
            - PENDING_DEACTIVATION_REQUEST
    PrerequisitesErrorDTO:
      type: object
      required:
        - code
        - message
        - details
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: string
          enum:
            - INITIATIVE_NOT_STARTED
            - INITIATIVE_END
            - BUDGET_TERMINATED
            - INITIATIVE_SUSPENDED
            - GENERIC_ERROR
    InitiativeDetailDTO:
      type: object
      properties:
        initiativeName:
          type: string
        status:
          type: string
        description:
          type: string
        ruleDescription:
          type: string
        endDate:
          type: string
          format: date
        rankingStartDate:
          type: string
          format: date
        rankingEndDate:
          type: string
          format: date
        rewardRule:
          $ref: '#/components/schemas/RewardValueDTO'
        refundRule:
          $ref: '#/components/schemas/InitiativeRefundRuleDTO'
        privacyLink:
          type: string
        tcLink:
          type: string
        logoURL:
          type: string
        updateDate:
          type: string
          format: date-time
    InitiativeRefundRuleDTO:
      type: object
      properties:
        accumulatedAmount:
          $ref: '#/components/schemas/AccumulatedAmountDTO'
        timeParameter:
          $ref: '#/components/schemas/TimeParameterDTO'
    AccumulatedAmountDTO:
      required:
        - accumulatedType
      type: object
      properties:
        accumulatedType:
          type: string
          enum:
            - BUDGET_EXHAUSTED
            - THRESHOLD_REACHED
        refundThreshold:
          type: number
    TimeParameterDTO:
      required:
        - timeType
      type: object
      properties:
        timeType:
          type: string
          enum:
            - CLOSED
            - DAILY
            - WEEKLY
            - MONTHLY
            - QUARTERLY
    RewardValueDTO:
      type: object
      allOf:
        - $ref: '#/components/schemas/InitiativeRewardRuleDTO'
        - type: object
          properties:
            rewardValue:
              maximum: 100
              minimum: 0
              type: number
    InitiativeRewardRuleDTO:
      required:
        - rewardValueType
      type: object
      properties:
        rewardValueType:
          type: string
          enum:
            - PERCENTAGE
            - ABSOLUTE
    RefundAdditionalInfoDTO:
      required:
        - identificationCode
      type: object
      properties:
        identificationCode:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
